apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "smartpeak-hosted.fullname" . }}
  labels:
    {{- include "smartpeak-hosted.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "smartpeak-hosted.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "smartpeak-hosted.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "smartpeak-hosted.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: grpc
              containerPort: 50051
              protocol: TCP
          # livenessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          # readinessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            {{- toYaml .Values.volumeMounts | default "" | nindent 12 }}
          volumeMounts:
          - mountPath: /sample-data
            name: sample-data
      volumes:
      # - name: sample-data
      #   hostPath:
      #     path: /d/data/
      #     type: Directory
      - name: sample-data
        flexVolume:
        driver: fstab/cifs
        fsType: cifs
        secretRef:
          name: smb-test
        options:
          networkPath: "\\ait-pdfs.win.dtu.dk\users\users6\s200370\data"
          mountOptions: "dir_mode=0755,file_mode=0755,noperm"
      {{- with .Values.nodeSelector }}
      # volumes:
      #   {{- toYaml .Values.volumes | default "" | nindent 8 }}
      # volumes:
      # - name: sample-data
      #   size: "5Gi"
      #   hostPath:
      #     path: /data
      # - name: data
      #   hostPath:
      #     path: /data
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
